# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70a89037b53025758d775d283415927ee4bb3521a8f9aa8f93ccd90ba11598fe195e6d04bd146914020ed622ac3dcac385d83844d903f120b03c86a4017a7f9

test:
  secret_key_base: 3c0af5218a9755e6481e8caf303f1d565f9cf532bc813b0afbe455c879afc6f002dc94b333c6351eb3190be548f40617c46c57a18fc11520c4466e99f3ca4480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
