# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 111de19380e0b3d2b0ec478c33c3711e6238032c4575517504e3d8b09c24777ee095003bf82a233d201cd3af2a985c34bfbb442d52ecc4f49466132437a2bc64

test:
  secret_key_base: c92c7c68e1d2632ca437b23de0b224f89ebb2435394d8b7ef475ab3c7253741d5e412fd9bcfcdf71a638cd4a595438cab1410f74bb9b1a9cbde31353a1cc1874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
